- name: ping machines
  ansible.builtin.ping:

- community.general.homebrew:
    name: nmap,wget,bat,tree,n,spectacle,romkatv/powerlevel10k/powerlevel10k,zsh
    state: latest

- name: Install formula foo with 'brew' from cask
  community.general.homebrew:
    name: homebrew/cask/phpstorm
    state: latest

- name: Install formula foo with 'brew' from cask
  community.general.homebrew:
    name: homebrew/cask/sublime-text
    state: present

- name: Install formula foo with 'brew' from cask
  community.general.homebrew:
    name: homebrew/cask/google-chrome
    state: present

- name: Install formula foo with 'brew' from cask
  community.general.homebrew:
    name: homebrew/cask/iterm2
    state: present

- name: Install formula foo with 'brew' from cask
  community.general.homebrew:
    name: homebrew/cask/clipy
    state: present

- name: Install formula foo with 'brew' from cask
  community.general.homebrew:
    name: homebrew/cask/spotify
    state: present