- name: install homebrew formulae
  community.general.homebrew:
    name: nmap,wget,bat,tree,n,zsh,romkatv/powerlevel10k/powerlevel10k
    state: present

- name: Install cask formulae
  homebrew_cask:
    name: phpstorm,spectacle,sublime-text,google-chrome,iterm2,clipy,spotify
    state: present
